// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDt9nFTDWBjXu5bYFRY2ithasPES9Ewh0',
    appId: '1:847806890216:web:bc0c271e5b2e1f7046495d',
    messagingSenderId: '847806890216',
    projectId: 'tasklist-11162',
    authDomain: 'tasklist-11162.firebaseapp.com',
    storageBucket: 'tasklist-11162.firebasestorage.app',
    measurementId: 'G-GQ33CMDQRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeCR5A-s8RTZeDtavEDiYmm9Jeqwf9dks',
    appId: '1:847806890216:android:e44290cf1c9d909c46495d',
    messagingSenderId: '847806890216',
    projectId: 'tasklist-11162',
    storageBucket: 'tasklist-11162.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5rW7xZnQZgbCL1MNt-AABJ6kbVgKY5Pc',
    appId: '1:847806890216:ios:70d8f70b6316e79e46495d',
    messagingSenderId: '847806890216',
    projectId: 'tasklist-11162',
    storageBucket: 'tasklist-11162.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5rW7xZnQZgbCL1MNt-AABJ6kbVgKY5Pc',
    appId: '1:847806890216:ios:70d8f70b6316e79e46495d',
    messagingSenderId: '847806890216',
    projectId: 'tasklist-11162',
    storageBucket: 'tasklist-11162.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDt9nFTDWBjXu5bYFRY2ithasPES9Ewh0',
    appId: '1:847806890216:web:14d6c48c6b75c57c46495d',
    messagingSenderId: '847806890216',
    projectId: 'tasklist-11162',
    authDomain: 'tasklist-11162.firebaseapp.com',
    storageBucket: 'tasklist-11162.firebasestorage.app',
    measurementId: 'G-9ZBQ99RSF5',
  );
}
